services:
  python-math-api:
    # Volume, so we can hot-reload code without rebuilding the image
    volumes:
      - ./app:/app
    # For dev, leave --reload on
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload